//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProjectExercise15
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.firmas = new HashSet<firma>();
        }
    
        public string cpr { get; set; }
        public string navn { get; set; }
        public string stilling { get; set; }
        public int loen { get; set; }
        public string postnr { get; set; }
    
        public virtual postnummer postnummer { get; set; }
        public virtual ICollection<firma> firmas { get; set; }
    }
}
