//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqProjectExercise15
{
    using System;
    using System.Collections.Generic;
    
    public partial class postnummer
    {
        public postnummer()
        {
            this.firmas = new HashSet<firma>();
            this.people = new HashSet<person>();
        }
    
        public string postnr { get; set; }
        public string postdistrikt { get; set; }
    
        public virtual ICollection<firma> firmas { get; set; }
        public virtual ICollection<person> people { get; set; }
    }
}
